#manipulator:
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_timeout: 0.05
#  solve_type: Manipulation1

manipulator:
  kinematics_solver: ur_kinematics/UR5_kinematics_plugin
	kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
	kinematics_solver_timeout: 0.005
